package ayre.enums;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

// Generated by GPT-5.6 Luna
/** Tests command names, aliases, and argument metadata. */
public class CommandTypeTest {
    @Test
    public void parseCommand_fullNamesAndAliases_returnsCommandType() {
        assertEquals(CommandType.BYE, CommandType.parseCommand("bye"));
        assertEquals(CommandType.BYE, CommandType.parseCommand("b"));
        assertEquals(CommandType.DELETE, CommandType.parseCommand("rm"));
        assertEquals(CommandType.EVENT, CommandType.parseCommand("event"));
    }

    @Test
    public void parseCommand_unknownInput_returnsNull() {
        assertNull(CommandType.parseCommand("unknown"));
    }

    @Test
    public void requiresArgs_andGetNumArgs_returnMetadata() {
        assertFalse(CommandType.BYE.requiresArgs());
        assertEquals(0, CommandType.BYE.getNumArgs());
        assertTrue(CommandType.EVENT.requiresArgs());
        assertEquals(3, CommandType.EVENT.getNumArgs());
    }
}
