package ayre;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

// Generated by GPT-5.6 Luna
/** Tests the high-level application response flow without mutating task data. */
public class AyreTest {
    @Test
    public void getResponse_bye_returnsTerminateSignal() {
        Ayre ayre = new Ayre();

        assertEquals("TERMINATE", ayre.getResponse("bye"));
    }

    @Test
    public void getResponse_unknownCommand_returnsErrorMessage() {
        Ayre ayre = new Ayre();

        assertEquals("~ ...Raven, this command was not found in the Coral Collective. Was it a mistake?",
                ayre.getResponse("unknown"));
    }
}
