package ayre;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.file.Path;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import ayre.enums.AyreStatus;
import ayre.enums.CommandType;
import ayre.storage.Storage;

// Generated by GPT-5.6 Luna
/** Tests dispatching command types to their command handlers. */
public class CommandExecutorTest {
    @TempDir
    Path tmpDir;

    @Test
    public void execute_todoCommand_dispatchesToTodoHandler() throws Exception {
        LiveTaskList tasks = new LiveTaskList(new TaskList(),
                new Storage(tmpDir.resolve("tasks.txt").toString()));
        CommandExecutor executor = new CommandExecutor(tasks);

        CommandResult result = executor.execute(CommandType.TODO, List.of("study"));

        assertEquals(AyreStatus.CONTINUE, result.status());
        assertEquals("~ New mission added:\n[T][ ] study", result.message());
        assertEquals(1, tasks.getNumTasks());
    }

    @Test
    public void execute_byeCommand_returnsTerminateStatus() throws Exception {
        LiveTaskList tasks = new LiveTaskList(new TaskList(),
                new Storage(tmpDir.resolve("tasks.txt").toString()));
        CommandExecutor executor = new CommandExecutor(tasks);

        assertEquals(AyreStatus.TERMINATE, executor.execute(CommandType.BYE, List.of()).status());
    }
}
