package ayre;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import ayre.tasks.Todo;

// Generated by GPT-5.6 Luna
/** Tests task mutations together with their persisted storage updates. */
public class LiveTaskListTest {
    @TempDir
    Path tmpDir;

    @Test
    public void add_persistsTaskAndUpdatesTaskCount() throws Exception {
        Path logPath = tmpDir.resolve("tasks.txt");
        LiveTaskList tasks = new LiveTaskList(new TaskList(), new Storage(logPath.toString()));

        assertEquals("~ New mission added:\n[T][ ] study", tasks.add(new Todo("study")));
        assertEquals(1, tasks.getNumTasks());
        assertEquals(List.of("T 0 study"), Files.readAllLines(logPath));
    }

    @Test
    public void markAndUnmark_persistCompletionState() throws Exception {
        Path logPath = tmpDir.resolve("tasks.txt");
        LiveTaskList tasks = new LiveTaskList(new TaskList(), new Storage(logPath.toString()));
        tasks.add(new Todo("study"));

        tasks.mark(0);
        assertEquals(List.of("T 1 study"), Files.readAllLines(logPath));
        tasks.unmark(0);
        assertEquals(List.of("T 0 study"), Files.readAllLines(logPath));
    }

    @Test
    public void findTasksAndDelete_reflectCurrentState() throws Exception {
        Path logPath = tmpDir.resolve("tasks.txt");
        LiveTaskList tasks = new LiveTaskList(new TaskList(), new Storage(logPath.toString()));
        tasks.add(new Todo("study"));

        assertEquals("~ These are the matching missions:\n1. [T][ ] study\n"
                + "~ Did you find what you were looking for, Raven?", tasks.findTasks("STUDY"));
        tasks.del(0);
        assertEquals(0, tasks.getNumTasks());
        assertEquals("", Files.readString(logPath));
    }
}
