package ayre;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;

import org.junit.jupiter.api.Test;

import ayre.tasks.Deadline;
import ayre.tasks.Todo;

// Generated by GPT-5.6 Luna
/** Tests adding, changing, searching, and formatting tasks in a TaskList. */
public class TaskListTest {
    @Test
    public void newTaskList_toString_returnsEmptyMessage() {
        assertEquals("~ The mission log is empty. \"Time to get to work\"... Raven.",
                new TaskList().toString());
    }

    @Test
    public void addTask_andToLog_returnsTaskDetails() {
        TaskList tasks = new TaskList();

        assertEquals("~ New mission added:\n[T][ ] study", tasks.addTask(new Todo("study")));
        assertEquals(1, tasks.getNumTasks());
        assertEquals(List.of("T 0 study"), tasks.toLog());
    }

    @Test
    public void findTasks_matchingName_returnsOnlyMatches() {
        TaskList tasks = new TaskList();
        tasks.addTask(new Todo("Study Java"));
        tasks.addTask(new Deadline("Buy milk", "2026-01-01"));

        assertEquals("~ These are the matching missions:\n1. [T][ ] Study Java\n"
                + "~ Did you find what you were looking for, Raven?", tasks.findTasks("java"));
        assertEquals("~ Sorry, Raven. There were no hits for that search.", tasks.findTasks("python"));
    }

    @Test
    public void markUnmarkAndDelete_updateListState() {
        TaskList tasks = new TaskList();
        tasks.addTask(new Todo("study"));

        assertEquals("~ Mission complete. Good work, Raven.\n[T][+] study", tasks.markTask(0));
        assertEquals("~ The mission is still pending, Raven. Let's get to it.\n[T][ ] study",
                tasks.unmarkTask(0));
        assertEquals("~ The mission has been dropped.\nDeleted: [T][ ] study", tasks.delTask(0));
        assertEquals(0, tasks.getNumTasks());
    }
}
