package ayre;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

// Generated by GPT-5.6 Luna
/** Tests validation of task indexes and ISO dates. */
public class ValidationToolsTest {
    @Test
    public void isInvalidTaskIndex_numericInput_returnsFalse() {
        assertFalse(ValidationTools.isInvalidTaskIndex("-12"));
        assertFalse(ValidationTools.isInvalidTaskIndex("0"));
    }

    @Test
    public void isInvalidTaskIndex_nonNumericInput_returnsTrue() {
        assertTrue(ValidationTools.isInvalidTaskIndex("1.5"));
        assertTrue(ValidationTools.isInvalidTaskIndex("one"));
    }

    @Test
    public void isInvalidIsoDate_validAndInvalidDates_returnExpectedResults() {
        assertFalse(ValidationTools.isInvalidIsoDate("2026-02-28"));
        assertTrue(ValidationTools.isInvalidIsoDate("2026-02-30"));
        assertTrue(ValidationTools.isInvalidIsoDate("not-a-date"));
    }

    @Test
    public void isInvalidDatePair_chronologicalDates_returnFalse() {
        assertFalse(ValidationTools.isInvalidDatePair("2026-01-01", "2026-01-01"));
        assertFalse(ValidationTools.isInvalidDatePair("2026-01-01", "2026-01-02"));
    }

    @Test
    public void isInvalidDatePair_reversedDates_returnTrue() {
        assertTrue(ValidationTools.isInvalidDatePair("2026-01-02", "2026-01-01"));
    }
}
