package ayre.tasks;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

// Generated by GPT-5.6 Luna
/** Tests formatting and persistence for Deadline tasks. */
public class DeadlineTest {
    @Test
    public void deadline_formatsDateForDisplayAndStorage() {
        Deadline deadline = new Deadline("submit report", "2026-02-03");

        assertEquals("[D][ ] submit report <by: Feb 03, 2026>", deadline.toString());
        assertEquals("D 0 submit report 2026-02-03", deadline.toLogString());
    }

    @Test
    public void deadline_completionIsIncludedInStorageFormat() {
        Deadline deadline = new Deadline("submit report", "2026-02-03");
        deadline.markComplete();

        assertEquals("D 1 submit report 2026-02-03", deadline.toLogString());
    }
}
