package ayre.tasks;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

// Generated by GPT-5.6 Luna
/** Tests formatting and persistence for Event tasks. */
public class EventTest {
    @Test
    public void event_formatsDatesForDisplayAndStorage() {
        Event event = new Event("conference", "2026-02-03", "2026-02-05");

        assertEquals("[E][ ] conference <from: Feb 03, 2026 to: Feb 05, 2026>", event.toString());
        assertEquals("E 0 conference 2026-02-03 2026-02-05", event.toLogString());
    }

    @Test
    public void event_completionIsIncludedInStorageFormat() {
        Event event = new Event("conference", "2026-02-03", "2026-02-05");
        event.markComplete();

        assertEquals("E 1 conference 2026-02-03 2026-02-05", event.toLogString());
    }
}
