package ayre.tasks;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

// Generated by GPT-5.6 Luna
/** Tests the behavior specific to Todo tasks and their shared Task state. */
public class TodoTest {
    @Test
    public void newTodo_formatsForDisplayAndStorage() {
        Todo todo = new Todo("study");

        assertFalse(todo.getComplete());
        assertEquals("[T][ ] study", todo.toString());
        assertEquals("T 0 study", todo.toLogString());
    }

    @Test
    public void taskState_canBeMatchedMarkedAndUnmarked() {
        Todo todo = new Todo("Study Java");

        assertTrue(todo.matchesName("java"));
        assertEquals("~ Mission complete. Good work, Raven.\n[T][+] Study Java", todo.markComplete());
        assertTrue(todo.getComplete());
        assertEquals("~ The mission is still pending, Raven. Let's get to it.\n[T][ ] Study Java",
                todo.unmarkComplete());
        assertFalse(todo.getComplete());
    }
}
